"""empty message

Revision ID: e1d05c96c1fb
Revises: 4369a1a76c88
Create Date: 2023-03-27 11:30:30.334261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e1d05c96c1fb"
down_revision = "4369a1a76c88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("email", type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
